### ISSUE TITLE
springboot 对于静态资源访问的配置

### ISSUE THREAD

**Issue by TaiDongX** [TaiDongX/movie_house#5]
spring默认的静态资源规则是：
```
classpath:/static
classpath:/public
classpath:/resources
classpath:/META-INF/resources
```

也可以自定义访问目录：
```
mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/
```
自定义之后，默认的目录会失效，访问的时候加上配置好路径就可以访问得到了
