### ISSUE TITLE
springboot 整合session

### ISSUE THREAD

**Issue by TaiDongX** [TaiDongX/movie_house#9]
web 容器的session的缺点：  

当一台机器的上的session变更后会将变更的数据以组播的形式分发给集群间的所有节点，对网络和所有的web容器都是存在开销。集群越大浪费越严重。不能做到线性的扩展。

而使用spring的session也就是共享处理方式是把所有的Web服务器都把session数据写到共享存储介质上（也就是redis），也都要来这台服务器获取session数据，通过这样的方式来实现Session数据的共享，网络开销较小。

springboot 集成session ：
导入依赖
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <!--spring-session-->
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
```

添加配置
```
spring:
 session:
    redis:
     store-type: redis
     flush-mode: on_save
     namespace: spring:session

 redis:
    host: 127.0.0.1
    #redis密码，没有密码的可以用～表示
    password: dw@@2020
    port: 6379

server:
  servlet:
    session:
      timeout: 3600

```
